apiVersion: v1
kind: Service
metadata:
  name: pipeln-backend
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: pipelnservices
spec:
  selector:
    app: pipeln-backend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
