name: Build and Test Frontend

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend

        steps:
            - uses: actions/checkout@v3

            - name: Use Node 18
              uses: actions/setup-node@v3
              with:
                node-version: "18.x"
                cache: 'npm'
                cache-dependency-path: "./frontend/package-lock.json"

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build --if-present

            - name: Test
              run: npm test
    