name: Build and Test Pipeln

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  acquire-infrastructure:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    defaults:
      run:
        working-directory: deployment/terraform
    outputs:
      storage_account_name: ${{ steps.tfout_san.outputs.storage_account_name }}
      acr_login_server: ${{ steps.tfout_als.outputs.acr_login_server }}
      acr_login_username: ${{ steps.tfout_alu.outputs.acr_login_username }}
      acr_login_password: ${{ steps.tfout_alp.outputs.acr_login_password }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        id: tfapply
        run: terraform apply --auto-approve

      - id: tfout_san
        run: echo "::set-output name=storage_account_name::$(terraform output storage_account_name)"

      - id: tfout_als
        run: echo "::set-output name=acr_login_server::$(terraform output acr_login_server)"

      - id: tfout_alu
        run: echo "::set-output name=acr_login_username::$(terraform output acr_login_username)"

      - id: tfout_alp
        run: echo "::set-output name=acr_login_password::$(terraform output acr_login_password)"

  build-and-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    needs: [build-and-test-frontend, acquire-infrastructure]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ needs.acquire-infrastructure.outputs.storage_account_name }}  --auth-mode key -d '$web' -s $GITHUB_WORKSPACE/frontend/build

      # - name: Purge CDN endpoint
      #   uses: azure/CLI@v1
      #   with:
      #       inlineScript: |
      #           az cdn endpoint purge --content-paths  "/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"

      - name: logout
        run: |
          az logout
        if: always()

  containerize-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services

    needs: [acquire-infrastructure]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ needs.acquire-infrastructure.outputs.acr_login_server }}
          username: ${{ needs.acquire-infrastructure.outputs.acr_login_username }}
          password: ${{ needs.acquire-infrastructure.outputs.acr_login_password }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ needs.acquire-infrastructure.outputs.acr_login_server }}/services:${{ github.sha }} ./backend
          docker push ${{ needs.acquire-infrastructure.outputs.acr_login_server }}/services:${{ github.sha }}

      - name: logout
        run: |
          az logout
        if: always()
